name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup the latest .NET 8 SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # This will use the latest 8.0 version

    # Publish the Blazor project to the release folder
    - name: Publish .NET Core Project
      run: dotnet publish AspNetCoreBlazorTest/AspNetCoreBlazorTest.csproj -c Release -o release --nologo

    # Deploy the published Blazor WASM project to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
